package sbnz.integracija;

import sbnz.integracija.example.facts.UserInfo;
import sbnz.integracija.example.facts.WorkoutInfo;
import sbnz.integracija.example.enums.BMICategory;
import sbnz.integracija.example.enums.WorkoutType;
import java.lang.Math;
import java.util.Random;

global Random random;

rule "User is malnourished Cardio"
    agenda-group "exercise_rest"
    when
    	$user: UserInfo( BMI == BMICategory.MALNOURISHED )
    	$wo: WorkoutInfo( muscleGroup == WorkoutType.CARDIO)
    then
        System.out.println("----> User is malnourished and is doing Cardio training, set the exercise time and rest time accordingly");
        modify($wo) {
            setExerciseDuration(25),
            setRestBetweenExercises(35);
        }
end


rule "User is obese Cardio"
    agenda-group "exercise_rest"
    when
    	$user: UserInfo( BMI == BMICategory.OBESE )
    	$wo: WorkoutInfo( muscleGroup == WorkoutType.CARDIO)
    then
        System.out.println("----> User is obese and is doing Cardio training, set the exercise time and rest time accordingly");
        modify($wo) {
            setExerciseDuration(30),
            setRestBetweenExercises(30);
        }
end


rule "User has normal BMI Cardio"
    agenda-group "exercise_rest"
    when
    	$user: UserInfo( BMI == BMICategory.NORMAL )
    	$wo: WorkoutInfo( muscleGroup == WorkoutType.CARDIO)
    then
        System.out.println("----> User has Normal BMI and is doing Cardio training, set the exercise time and rest time accordingly");
        modify($wo) {
            setExerciseDuration(45),
            setRestBetweenExercises(15);
        }
end


rule "User is malnourished Strength"
    agenda-group "exercise_rest"
    when
    	$user: UserInfo( BMI == BMICategory.MALNOURISHED )
    	$wo: WorkoutInfo( muscleGroup != WorkoutType.CARDIO)
    then
        System.out.println("----> User is malnourished and is doing Strenght training");
        modify($wo) {
            setRestBetweenSets(45),
            setRestBetweenExercises(60),
            //setRepetitions(random.nextInt(3)+6),
            setNumberOfSets(3),
            setNumberOfExercises(4);
        }
end

rule "User is obese Strength"
    agenda-group "exercise_rest"
    when
    	$user: UserInfo( BMI == BMICategory.OBESE )
    	$wo: WorkoutInfo( muscleGroup != WorkoutType.CARDIO)
    then
        System.out.println("----> User is obese and is doing Strenght training");
        modify($wo) {
            setRestBetweenSets(60),
            setRestBetweenExercises(90),
            //setRepetitions(random.nextInt(3)+10),
            setNumberOfSets(random.nextInt(3)+1),
            setNumberOfExercises(4);
        }
end


rule "User has normal BMI Strength"
    agenda-group "exercise_rest"
    when
    	$user: UserInfo( BMI == BMICategory.NORMAL )
    	$wo: WorkoutInfo( muscleGroup != WorkoutType.CARDIO)
    then
        System.out.println("----> User has Normal BMI and is doing Strenght training");
        modify($wo) {
            setRestBetweenSets(30),
            setRestBetweenExercises(90),
            setRepetitions(random.nextInt(5)+12),
            setNumberOfSets(random.nextInt(3)+2),
            setNumberOfExercises(6);
        }
end